# PCA practice with creditcard fraud dataset


## Importing libraries

In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df =  pd.read_csv(r"C:\Users\nabil\OneDrive\Desktop\IBM data science professional certificate\Anomaly detection\Credit card fraud\creditcard.csv")

In [67]:
df.shape

(284807, 31)

In [68]:
df = df.rename(columns={'Class': 'Category'})

In [70]:
nor_obs = df.loc[df.Category==0]    #Data frame with normal observation
ano_obs = df.loc[df.Category==1]    #Data frame with anomalous observation

In [71]:
train_feature = nor_obs.loc[0:200000, :]
train_feature = train_feature.drop('Category', 1)
Y_1 = nor_obs.loc[200000:, 'Category']
Y_2 = ano_obs['Category']

In [72]:
X_test_1 = nor_obs.loc[200000:, :].drop('Category',1)
X_test_2 = ano_obs.drop('Category',1)
X_test = X_test_1.append(X_test_2)

In [73]:
oneclass = svm.OneClassSVM(kernel='linear', gamma=0.001, nu=0.95)
Y_1 = nor_obs.loc[200000:, 'Category']
Y_2 = ano_obs['Category']

Y_test= Y_1.append(Y_2)

In [6]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Category  
0 -0.189115  0.133558 -0.021053  149.62         0  
1  0.125895 -0.008983  0.014724    2.69         0  
2 -0.139097 -0.055353 -0.059752  378.66         0  
3 -0.221929  0.062723  0.061458  123.50         0  
4  0.502292  0.219422  0.215153   69.99         0  

[5 rows x 31 columns]

In [13]:
X = df.iloc[: , 0:30].values
y = df.iloc[: , 30].values

### Applying standard scaling

In [15]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X) 

## Applying principal component analysis

In [18]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=3)
Y_sklearn = sklearn_pca.fit_transform(X_std)

### Finding Singular value decomposition (SVD)

In [27]:
#u,s,v = np.linalg.svd(X_std.T)

from sklearn.utils.extmath import randomized_svd

U, S, V = randomized_svd(X_std, 
                              n_components=31,
                              n_iter=5,
                              random_state=None)

In [41]:
# Eigenvectors
U

array([[ 5.57880139e-04, -3.65738529e-03, -1.30523952e-03, ...,
         1.56804593e-03,  9.19535087e-04, -1.90173865e-04],
       [-5.26845515e-04, -2.99983689e-03, -1.00064920e-03, ...,
        -1.89331217e-03,  2.54904595e-03,  1.36020750e-04],
       [ 2.50200926e-03, -3.65858780e-03,  2.68424402e-04, ...,
        -1.18235741e-03,  7.12081816e-04,  1.23449085e-03],
       ...,
       [-2.59856438e-04,  2.99039615e-03,  1.22164248e-04, ...,
        -2.04884886e-04, -8.16915051e-04, -3.57840205e-05],
       [-6.24106892e-04,  1.76957392e-03, -3.03890969e-04, ...,
         1.63648232e-03, -3.59504751e-03,  2.21357760e-04],
       [ 1.02783378e-03,  2.75228793e-03,  8.04375418e-05, ...,
         5.26262083e-04, -1.50211660e-03,  9.92940800e-04]])

In [40]:
#Eigenvalues
S 

array([746.80996609, 692.47948309, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       533.67312093, 533.67312093, 533.67312093, 533.67312093,
       299.94837618, 109.57194748])

## Calculating varience retained

In [30]:
tot = sum(S)
var_exp = [(i / tot)*100 for i in sorted(S, reverse=True)]
cum_var_exp = np.cumsum(var_exp)

In [45]:
# Varience retaind with every principal components
cum_var_exp

array([  4.7493971 ,   9.15327519,  12.54721164,  15.9411481 ,
        19.33508456,  22.72902102,  26.12295747,  29.51689393,
        32.91083039,  36.30476685,  39.6987033 ,  43.09263976,
        46.48657622,  49.88051268,  53.27444913,  56.66838559,
        60.06232205,  63.45625851,  66.85019497,  70.24413142,
        73.63806788,  77.03200434,  80.4259408 ,  83.81987725,
        87.21381371,  90.60775017,  94.00168663,  97.39562308,
        99.30316853, 100.        ])

In [43]:
print('By using 3 principal components retaind varience is: ', cum_var_exp[2])

By using 3 principal components retaind varience is:  12.547211642708604


# Detecting anomalies with new reduced data set

In [47]:
Y_sklearn.shape

(284807, 3)